openapi: 3.0.3
info:
    title: 'JUMGA FOR FLUTTERWAVE API'
    description: 'This is the api docs for backend implementation'
    version: 1.0.0
servers:
    -
        url: 'http://localhost'
paths: []
